apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-rwx
spec:
  capacity:
    storage: 5Gi		# 실제 디스크 용량 X , 디스크를 5Gi로 분할 X , PVC 요청서에 대한 매칭값

  volumeMode: Filesystem	# FileSystem형태로 pod에게 제공 (디렉터리 처럼 사용)

  accessModes:
    - ReadWriteMany	# 여러 노드의 pod들이 사용 가능

  persistentVolumeReclaimPolicy: Retain		# PVC가 삭제되어도 데이터는 삭제하지 않는다.

  nfs:
    server: 192.168.111.100
    path: /export/k8s
