apiVersion: v1
kind: Pod
metadata:
  name: web-hostpath

spec:
  volumes:
  - name: html
    hostPath:
      path: /webdata

  containers:
    - name: nginx-container
      image: nginx:1.29.1

      volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html
