apiVersion: v1
kind: Pod
metadata:
  name: multipod
spec:
  containers:
  - name: nginx-container
    image: nginx:1.29.1
    ports:
    -  containerPort: 80
  - name: centos-container
    image: centos:7
    command:
    - sleep
    - "10000"
